name: Deploy on the server

on:
  push:
    branches: [ production ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Deploy project
      uses: appleboy/ssh-action@master
      with:
        host: pointlessapps.tech
        username: rzeAssistant
        password: ${{ secrets.SFTP_PASSWORD }}
        script: |
          cd projekt &&
          git checkout create-controller-specs-i23 &&
          git pull &&
          cd backend &&
          npm install && npm run build
