name: Deploy on the server

on:
  push:
    branches: [ production ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build project
      run: |
        npm install
        npm run build
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: sftp://pointlessapps.tech
        ftp-username: rzeAsistant
        ftp-password: ${{ secrets.SFTP_PASSWORD }}
        git-ftp-args: --insecure --dry-run
        local-dir: dist
