name: Deploy on the server

on:
  push:
    branches: [ production ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build project
      run: |
        npm install
        npm run build --if-present
    - name: Deploy project
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: rzeAssistant
        server: pointlessapps.tech
        private_key: ${{ secrets.SSH_KEY }} 
        local_path: './backend/dist*'
        remote_path: '/home/rzeAssistant'
