name: Backend test checking

on:
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn test
    - name: Run formatter
      run: yarn format:check
    - name: Run name check
      shell: bash
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        hub issue show -f "%t" $(git rev-parse --abbrev-ref HEAD | rev | cut -d '/' -f2 | rev) >/dev/null 2>/dev/null || ( echo 'Issue with id of the branch does not exist' && exit 1 )
        [[ $(git rev-parse --abbrev-ref HEAD) =~ ^([a-z]+-)+i[0-9]+$ ]] || ( echo 'Branch is named not correctly' && exit 1 )
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
